"use client";
import {useState} from "react";
import {Area,AreaChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis,BarChart,Bar} from "recharts";
import {Panel} from "@/components/soc-ui";
import {humanize} from "@/lib/utils";
const tooltipStyle={background:"var(--card)",border:"1px solid var(--border)",borderRadius:8,fontSize:11,color:"var(--foreground)"};
export function IncidentChart({days,hours}:{days:{time:string;incidents:number}[];hours:{time:string;incidents:number}[]}){
  const [period,setPeriod]=useState("7d");
  return <Panel title="Incident activity" subtitle="Investigations created · UTC" action={<div className="flex rounded-md border p-0.5">{["24h","7d"].map(p=><button key={p} onClick={()=>setPeriod(p)} aria-pressed={p===period} className={`rounded px-2.5 py-1 text-[10px] ${p===period?"bg-muted text-foreground":"text-muted-foreground"}`}>{p}</button>)}</div>}><div className="h-[205px] p-4 pl-1" role="img" aria-label={`Incidents over ${period}: ${(period==="7d"?days:hours).map(d=>`${d.time}: ${d.incidents}`).join(", ")}`}><ResponsiveContainer width="100%" height="100%"><AreaChart data={period==="7d"?days:hours}><defs><linearGradient id="incident-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#78e8c3" stopOpacity={.2}/><stop offset="100%" stopColor="#78e8c3" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 5"/><XAxis dataKey="time" axisLine={false} tickLine={false} tick={{fill:"var(--muted-foreground)",fontSize:10}} minTickGap={35}/><YAxis allowDecimals={false} axisLine={false} tickLine={false} tick={{fill:"var(--muted-foreground)",fontSize:10}} width={30}/><Tooltip contentStyle={tooltipStyle}/><Area type="monotone" dataKey="incidents" stroke="#78e8c3" strokeWidth={2} fill="url(#incident-fill)" isAnimationActive={false}/></AreaChart></ResponsiveContainer></div></Panel>;
}
export function Distribution({data,title}:{data:{name:string;value:number}[];title:string}){const max=Math.max(...data.map(d=>d.value),1);return <Panel title={title} subtitle="Past 7 days · simulated events"><div className="space-y-4 p-5">{data.map(d=><div key={d.name}><div className="mb-2 flex justify-between text-[11px]"><span className="capitalize text-muted-foreground">{humanize(d.name)}</span><span className="mono">{d.value.toLocaleString("en-US")}</span></div><div className="h-1 rounded-full bg-muted"><div className="h-1 rounded-full bg-primary/65" style={{width:`${Math.max(1,(d.value/max)*100)}%`}}/></div></div>)}</div></Panel>;}
export function ScoreChart({data}:{data:{time:string;score:number}[]}){return <Panel title="Security posture" subtitle="Hourly score · synthetic historical baseline"><div className="h-[160px] p-4" role="img" aria-label={`Security score history, latest ${data.at(-1)?.score??"unavailable"} out of 100`}><ResponsiveContainer width="100%" height="100%"><BarChart data={data.filter((_,i)=>i%6===0)}><XAxis hide dataKey="time"/><YAxis hide domain={[0,100]}/><Tooltip contentStyle={tooltipStyle} labelFormatter={label=>String(label).slice(0,16).replace("T"," ")+" UTC"}/><Bar dataKey="score" fill="#78e8c3" fillOpacity={.5} radius={[2,2,0,0]} isAnimationActive={false}/></BarChart></ResponsiveContainer></div></Panel>;}
