import type { EventInput, EventType } from "@/lib/domain";
export function seededRandom(seed: number) {
  let state = seed >>> 0;
  return () => {
    state = (state + 0x6d2b79f5) >>> 0;
    let value = Math.imul(state ^ (state >>> 15), state | 1);
    value ^= value + Math.imul(value ^ (value >>> 7), value | 61);
    return ((value ^ (value >>> 14)) >>> 0) / 4294967296;
  };
}
const weighted: [EventType, number][] = [
  ["NORMAL_LOGIN", 64],
  ["FAILED_LOGIN", 18],
  ["NEW_DEVICE", 6],
  ["NEW_COUNTRY", 4],
  ["BRUTE_FORCE", 2],
  ["PRIVILEGE_ESCALATION", 2],
  ["MALWARE_DETECTED", 1],
  ["SUSPICIOUS_DOWNLOAD", 2],
  ["API_ABUSE", 1],
];
export function generateEvent(
  counter: number,
  identity: { id: string; homeCountry: string },
  assetId: string | null,
  now = new Date(),
): EventInput {
  const random = seededRandom(Math.imul(counter + 2026, 2654435761));
  let roll = random() * 100;
  let type: EventType = "NORMAL_LOGIN";
  for (const [candidate, weight] of weighted) {
    roll -= weight;
    if (roll < 0) {
      type = candidate;
      break;
    }
  }
  const countryCode = type === "NEW_COUNTRY" ? "SG" : identity.homeCountry;
  return {
    source: "pulseops-simulator",
    sourceEventId: `tick-${counter}`,
    type,
    category:
      type === "API_ABUSE"
        ? "API"
        : ["MALWARE_DETECTED", "NEW_DEVICE"].includes(type)
          ? "ENDPOINT"
          : type === "SUSPICIOUS_DOWNLOAD"
            ? "DATA"
            : type === "PRIVILEGE_ESCALATION"
              ? "IDENTITY"
              : "AUTHENTICATION",
    severity:
      type === "MALWARE_DETECTED"
        ? "CRITICAL"
        : ["API_ABUSE", "PRIVILEGE_ESCALATION", "BRUTE_FORCE"].includes(type)
          ? "HIGH"
          : ["FAILED_LOGIN", "SUSPICIOUS_DOWNLOAD"].includes(type)
            ? "MEDIUM"
            : "LOW",
    occurredAt: now,
    identityId: identity.id,
    assetId,
    ipAddress: `203.0.113.${1 + (counter % 250)}`,
    countryCode,
    metadata: {
      detail: "Synthetic telemetry generated by PulseOps. No network action was performed.",
    },
  };
}
